import 'package:flutter/material.dart';

import 'app_localizations.dart';

extension MyWords on Words {
  String tr(BuildContext context, [int? key]) => AppLocalizations.of(context).tr("$name${key ?? ""}");
}

enum Words {
  homeMainWord,
  menu,
  appName,
  myCards,
  sTypeFirst,
  sTypeSecond,
  sTypeThird,
  sTypeFourth,
  sTypeFive,

  ///for home page
  qrCodeScan,
  statusForProfile,
  standardForProfile,
  payment,
  transfer,
  marketPartner,
  home,
  deal,
  profile,
  addCardForActive,
  homeWaitingVerification,
  failedVerificationNotificationText,
  goVerification,
  begin,
  doneVerificationNotificationText,
  waitingMessage,
  limitation,
  cashback,

  ///for linking QR Page
  addingCardButton,
  addingCardTitle1,
  addingCardContent1,
  addingCardTitle2,
  addingCardContent2,
  addingCardTitle3,
  addingCardContent3,
  qRPayment,
  confirmCard,
  connectCardMassage,
  smsConfirmation,
  phoneNumber,
  proceed,
  smsHasBeenSent,
  toNumber,
  errorCode,
  receiveACode,
  forward,
  connectTheCard,

  /// for Transfer Card to Card
  moneyTransaction,
  cardNumberOrPhone,
  enterCardNumberOrPhone,
  holloway,
  transferAmount,
  specifyTransferAmount,
  paySumma,
  chooseCardTransfer,
  transferFromCardToCard,
  limit,
  checkPayment,
  pressing,
  translate,
  youAgree,
  publicOffer,
  selectCard,
  working,
  balance,
  paymentSuccessfully,
  paymentFailed,
  cardRefill,

  ///for process register page
  identification,
  personalDate,
  addressOfResidence,
  fio,
  mockName,
  serPassport,
  aa,
  passportNumber,
  mock0998765,
  falseCustomSubtitle,
  trueCustomSubtitle,
  repeat,
  waiting,
  fail,
  dateOfBirth,
  mockDateOfBirth,
  mockAddress,

  /// for rassrochki page
  installment,
  creditLimit,
  payInInstallments,
  overpayments,
  downPayment,
  niceBonuses,
  surcharge,
  installmentPeriod,

  /// for Activation Card
  cardActivation,
  holderName,
  cardActivated,
  cardActivatedContent,

  /// for intro page
  skip,
  register,
  enjoyBonusesZpay,
  partnerCashbackZpay,
  partnerStoresWithProduct,
  findStoresByCategoryLocation,
  viewAndManage,
  manageYourDataInApp,
  purchaseZpay2Minutes,
  buyPay6MonthsPassportPaymentCard,

  /// for create pin code
  setPIN,
  verifyPIN,
  enterPIN,
  unlockFaceID,
  delete,
  successEnterVerificationCode,
  success,
  verifyCodeIncorrect,
  passwordIncorrectTryAgain,
  biometricEnabled,
  biometricDisabled,
  addCard,
  close,
  addingCards,
  chooseCardDesign,
  cardExpiryDate,
  dateYearExpiration,
  cardName,
  giveCardName,
  cardNumber,
  cardHolderName,
  expiryDate,
  exampleName,
  errorAddingCard,
  tryAgain,
  cardAdded,
  yourSuccessfullyAddedCard,
  pleaseAddCard,
  noCardsAvailable,

  /// login pages
  codeNotCome,
  wrongCode,
  time,
  phoneVerification,
  phoneVerification2,
  numberVerification,
  ru,
  enterNumber,

  ///payment qr code
  qrPayment,
  off,
  on,
  sum,
  pay,
  paymentSuccess,
  aboutPayment,
  ready,
  paymentError,
  payAuthCode,
  AID,
  card,
  paymentAmount,
  check,
  goBackMainPage,
  selectPaymentMethod,

  ///for notification page
  notification,
  contract,
  deletionHistory,
  showAll,
  markAsRead,
  noActiveContracts,
  uz,
  chooseNumber,
  toEnter,

  ///drawer
  drawerVerification,
  status,
  standard,
  bronze,
  silver,
  gold,
  callCenter,
  exit,
  chatWords,
  installmentPlan,
  version,
  update,
  setting,
  notificationSetting,
  offer,

  ///my contract page
  myContracts,
  bid,
  amountPayment,
  remainder,
  totalContractAmount,
  payOfEarly,
  writeOffAmount,
  earlyRepayment,
  thereAreNoAvailableFoundCard,
  pleaseTopUpCard,
  paymentSchedule,
  youHaveNoContract,
  repay,
  personalAccount,
  orderZpayCard,
  orderCardGetBonus,
  registrationZpayService,
  frequentlyAskedQuestion,
  belowList,
  mobCon,
  internet,
  filmTV,
  entertainment,
  webWallet,
  publicService,
  telephone,
  communal,
  shelters,
  mobileConnection,
  chooseCompany,
  replenishmentAmount,
  monitoring,
  partner,
}
